// tasks-react/src/components/contact/contact.js
import './contact.scss';

function Contact() {
  return (
    <form id="contact-form" action="" className="contact-form" novalidate>
      <p className="contact-form__title">Contact us</p>
      
      <label for="cf_email" className="contact-form__label">Your email</label>
      <input type="email" className="contact-form__input" name="cf_email" id="cf_email" required />

      <label for="cf_subject" className="contact-form__label">Subject</label>
      <input type="text" className="contact-form__input" name="cf_subject" id="cf_subject" required />

      <label for="cf_message" className="contact-form__label">Your message</label>
      <textarea maxlength="280" row="6" name="cf_message" id="cf_message" className="contact-form__textarea" required></textarea>
      <span className="contact-form__count"><strong>280</strong> characters left</span>

      <label for="cf_file" className="contact-form__label">Upload a file</label>
      <input type="file" name="cf_files[]" id="cf_file" multiple />

      <button className="button contact-form__submit" type="submit">Send message</button>
    </form>
    
  )
}

export default Contact;

// tasks-angular/src/app/contact/contact.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.scss']
})
export class ContactComponent implements OnInit {
  emailField = '';
  emailPattern = /\S+@\S+\.\S+/;
  isEmailValid = this.emailPattern.test(this.emailField);
  
  

  constructor() { }

  ngOnInit(): void {

  }
  onSubmit(): void {
    console.log(this.emailField);
    console.log(this.isEmailValid);
    
  }

}

<form id="contact-form" action="" class="contact-form" (submit)="onSubmit()">
  <p class="contact-form__title">Contact us</p>

  <label for="cf_email" class="contact-form__label">Your email</label>
  <input
    type="email"
    class="contact-form__input"
    name="cf_email"
    id="cf_email"
    [(ngModel)]="emailField"
    required
  />

  <label for="cf_subject" class="contact-form__label">Subject</label>
  <input
    type="text"
    class="contact-form__input"
    name="cf_subject"
    id="cf_subject"
    required
  />

  <label for="cf_message" class="contact-form__label">Your message</label>
  <textarea
    maxlength="280"
    row="6"
    name="cf_message"
    id="cf_message"
    class="contact-form__textarea"
    required
  ></textarea>
  <span class="contact-form__count"><strong>280</strong> characters left</span>

  <label for="cf_file" class="contact-form__label">Upload a file</label>
  <input type="file" name="cf_files[]" id="cf_file" multiple />

  <button class="button contact-form__submit" type="submit">
    Send message
  </button>
</form>
