// tasks-react/src/components/client/client.js
import './client.scss';

function Client({data}) {
  // Posso tb fazer o destructuring const {name, id} = data

  return (
        <div className="client" data-status="active">
          <input
          type="text"
          className="client__title"
          value={data.name}
          name={`client_${data.id}`}
          readOnly
        />
        <button className="client__edit">
          <span className="material-icons">create</span>
        </button>
        <button className="client__delete">
          <span className="material-icons">delete</span>
        </button>
        <button className="client__restore">
          <span className="material-icons">restore</span>
        </button>
      </div>
  )
};

export default Client;

// tasks-angular/src/app/client/client.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Client } from 'src/interfaces/clients';

@Component({
  selector: 'app-client',
  templateUrl: './client.component.html',
  styleUrls: ['./client.component.scss']
})
export class ClientComponent implements OnInit {

  @Input() info!: Client;
  @Input() search!: string;
  @Output() updateClientEvent = new EventEmitter<Client>();

  isEditing = false;

  constructor() { }

  ngOnInit(): void {
  }

  onEdit(): void {
    this.isEditing = true;
  }

  onBlur(): void {
    this.isEditing = false;
  }

  onChange(): void {
    this.updateClientEvent.emit(this.info);
  }

  onDelete(): void {
    this.info.isActive = false;

    this.updateClientEvent.emit(this.info);
  }

  onRestore(): void {
    this.info.isActive = true;
    this.updateClientEvent.emit(this.info);
  }
}

<div
  [attr.data-search-hide]="
    info.name.toLowerCase().includes(search.toLowerCase()) ? null : ''
  "
  [attr.data-status]="info.isActive ? 'active' : 'archived'"
  class="client"
>
  <input
    type="text"
    class="client__title"
    name="client_1"
    (blur)="onBlur()"
    (change)="onChange()"
    [(ngModel)]="info.name"
    [attr.readonly]="isEditing ? null : 'readonly'"
  />
  <button class="client__edit" (click)="onEdit()">
    <span class="material-icons">create</span>
  </button>
  <button *ngIf="info.isActive" class="client__delete" (click)="onDelete()">
    <span class="material-icons">delete</span>
  </button>
  <button *ngIf="!info.isActive" class="client__restore" (click)="onRestore()">
    <span class="material-icons">restore</span>
  </button>
</div>
