// tasks-angular/src/app/team/team.component.ts
import { Component, OnInit } from '@angular/core';
import { Member } from 'src/interfaces/members';
import { MEMBERS } from 'src/mocks/members-mock';

@Component({
  selector: 'app-team',
  templateUrl: './team.component.html',
  styleUrls: ['./team.component.scss']
})
export class TeamComponent implements OnInit {
  members = MEMBERS;
  rate = 0;

  constructor() { }

  ngOnInit(): void {
    const data = localStorage.getItem('members');
    if(data) {
      this.members = JSON.parse(data);
    } else {
      this.getMembersFromAPI();
    }
  }

  getMembersFromAPI(): void {
    const roles = ['Project Manager', 'Frontend Developer', 'Backend Developer', 'UI Designer', 'UX Designer', 'Tech Lead', 'QA'];

    fetch('https://jsonplaceholder.typicode.com/users')
        .then(response => response.json())
        .then(data => {
            for (let item of data) {
                const random = Math.floor(Math.random() * roles.length);
                item.role = roles[random];
                item.rate = 0;
            }
            this.members = data;
            // Adicionar ao Local storage e stringify da data
            localStorage.setItem('members', JSON.stringify(data));
        });
  }

  onInputBlur(member: Member): void {
    this.rate = member.rate;
    localStorage.setItem('members', JSON.stringify(this.members));
  }

}

<section class="team">
  <header class="team__header">
    <h2 class="team__headline">Members</h2>
  </header>
  <table class="team__table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Billable rate</th>
        <th>Role</th>
      </tr>
    </thead>
    <tbody *ngFor="let member of members">
      <tr>
        <td>{{ member.name }}</td>
        <td>{{ member.email }}</td>
        <td class="team__rate">
          <input
            type="number"
            name="team_member_1"
            value="{{ member.rate }}"
            [attr.data-id]="member.id"
            [(ngModel)]="member.rate"
            (blur)="onInputBlur(member)"
          />
          <span>€</span>
        </td>
        <td>
          <span class="team__role" [attr.data-role]="member.role">{{
            member.role
          }}</span>
        </td>
      </tr>
    </tbody>
  </table>
</section>

// tasks-react/src/components/team/team.js
import './team.scss'

function Team() {
  return (
    <section className="team">
        <header className="team__header">
          <h2 className="team__headline">Members</h2>
        </header>
        <table className="team__table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Billable rate</th>
              <th>Role</th>
            </tr>
          </thead>
          <tbody>
              <tr>
              <td>Rodrigo Castro (you)</td>
              <td>ola@rodrigo.com</td>
              <td className="team__rate">
                <input type="text" name="team_member_1" value="0" />
                <span>€</span>
              </td>
              <td>
                <span className="team__role">Owner</span>
              </td>
            </tr>
          </tbody>
        </table>
    </section>
  )
}

export default Team
