// tasks-angular/src/app/clients/clients.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-clients',
  templateUrl: './clients.component.html',
  styleUrls: ['./clients.component.scss']
})
export class ClientsComponent implements OnInit {
  title = 'Clients works!';
  clients = [
    {
      id: 1,
      name: 'Others',
      isActive: true
    },
    {
      id: 2,
      name: 'Farfetch',
      isActive: true
    },
    {
      id: 3,
      name: 'Worten',
      isActive: true
    },
  ];

  constructor() { }

  ngOnInit(): void {
  }

}

<!-- Clients -->
<section class="clients">
  <header class="clients__header">
    <h2 class="clients__headline">{{title}} </h2>
    <!--
    <div class="clients__filters">
      <select name="clients_filter" id="" class="clients__select">
        <option value="active">Show active</option>
        <option value="archived">Show archived</option>
        <option value="">Show all</option>
      </select>
      <input
      type="search"
      class="clients__input"
      name="clients_search"
      placeholder="Search by name"
      />
    </div>
    <form action="#nowhere" class="clients__create">
      <input
      type="text"
      name="create_client"
      class="clients__input"
      placeholder="Add new client"
      />
      <button type="submit" class="button clients__add" disabled>
        Add
      </button>
    </form>
    -->
  </header>
  <div class="clients__container" data-status="active">
    <p class="clients__label">Name</p>

    <div *ngFor="let client of clients" class="client">
      <span class="client__title">{{client.name}}</span>
      <!-- <input
      type="text"
      class="client__title"
      value="Others"
      name="client_1"
      readonly
      /> -->
      <button class="client__edit">
        <span class="material-icons">create</span>
      </button>
      <button class="client__delete">
        <span class="material-icons">delete</span>
      </button>
      <button class="client__restore">
        <span class="material-icons">restore</span>
      </button>
    </div> 
  </div>
</section>

// tasks-react/src/components/clients/clients.js
import Client from '../client/client'

import './clients.scss'

function Clients() {
  const data = [
    {
      id: 1,
      name: 'Worten',
      isActive: true
    },
    {
      id: 2,
      name: 'Fnac',
      isActive: true
    },
    {
      id: 3,
      name: 'BMW',
      isActive: false
    },
    {
      id: 4,
      name: 'Apple',
      isActive: true
    },
    {
      id: 5,
      name: 'Microsoft',
      isActive: true
    },
  ];
  
  return (
    <section className="clients">
      <header className="clients__header">
        <h2 className="clients__headline">Clients</h2>
        <div className="clients__filters">
          <select name="clients_filter" id="" className="clients__select">
            <option value="active">Show active</option>
            <option value="archived">Show archived</option>
            <option value="">Show all</option>
          </select>
          <input
            type="search"
            className="clients__input"
            name="clients_search"
            placeholder="Search by name"
          />
        </div>
        <form action="#nowhere" className="clients__create">
          <input
            type="text"
            name="create_client"
            className="clients__input"
            placeholder="Add new client"
          />
          <button type="submit" className="button clients__add" disabled>
            Add
          </button>
        </form>
      </header>
      <div className="clients__container" data-status="active">
      <p className="clients__label">Name</p>
    
        {data.map(client => (
          <Client key={client.id} data={client}/>
        ))}

      </div>
    </section>
  )
}

export default Clients
